---
- name: "Add Node.js"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sude -E bash -

- name: "Install Node.js 13"
  become: true
  apt:
    name: ["node.js"]
    state: latest
    update_cache: yes

- name: "Install PM2"
  npm:
    name: pm2
    global: yes
